title: The Cloud Native Computer Project
logo: https://avatars3.githubusercontent.com/u/49678748?s=400&u=23aa86cbd4f8d9a5b2c2a8cc744c4d364903a772
description: A continuously integrating, continuously deploying cloud computer.
show_downloads: false
google_analytics: UA-138590222-1
theme: jekyll-theme-minimal
