version: '3.5'

services:

  code:
    image: codercom/code-server:latest
    command: code-server --data-dir $CLOUD_COMPUTER_CODE --no-auth $CLOUD_COMPUTER_BACKEND
    restart: always
    tty: true
    labels:
      namespace: code
      tier: cloud-computer
    environment:
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DISPLAY: $CLOUD_COMPUTER_XEPHYR_DISPLAY
      DOCKER_HOST: localhost
      GIT_AUTHOR_EMAIL: $GIT_AUTHOR_EMAIL
      GIT_AUTHOR_NAME: $GIT_AUTHOR_NAME
      GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
      GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
      CLOUD_COMPUTER_CERTIFICATES: $CLOUD_COMPUTER_CERTIFICATES
      CLOUD_COMPUTER_HOST_DNS: $CLOUD_COMPUTER_HOST_DNS
      CLOUD_COMPUTER_HOST_ID: $CLOUD_COMPUTER_HOST_ID
      CLOUD_COMPUTER_TMUX: $CLOUD_COMPUTER_TMUX
    expose:
      - 8443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - CLOUD_COMPUTER_BACKEND:$CLOUD_COMPUTER_BACKEND
      - CLOUD_COMPUTER_CERTIFICATES:$CLOUD_COMPUTER_CERTIFICATES:ro
      - CLOUD_COMPUTER_CODE:$CLOUD_COMPUTER_CODE
      - CLOUD_COMPUTER_CODE_SERVER:$CLOUD_COMPUTER_CODE_SERVER
      - CLOUD_COMPUTER_FRONTEND:$CLOUD_COMPUTER_FRONTEND
      - CLOUD_COMPUTER_SLACKBOT:$CLOUD_COMPUTER_SLACKBOT
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX

volumes:
  CLOUD_COMPUTER_BACKEND:
  CLOUD_COMPUTER_CERTIFICATES:
  CLOUD_COMPUTER_CODE:
  CLOUD_COMPUTER_CODE_SERVER:
  CLOUD_COMPUTER_FRONTEND:
  CLOUD_COMPUTER_SLACKBOT:
  CLOUD_COMPUTER_TMUX:
