version: '3.5'

networks:
  backend:
    driver: bridge

services:

  docker:
    image: bobtfish/docker-socket-http-proxy
    restart: always
    expose:
      - 2375
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:docker.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=2375
      - traefik.protocol=http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
