version: '3.5'

networks:
  backend:
    driver: bridge

services:

  docker:
    image: sjawhar/docker-socket-proxy
    restart: always
    command:
      - -dd
      - -lmlocal2
    environment:
      CERTS_DIR: $CLOUD_COMPUTER_DOCKER
    expose:
      - 2376
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:docker.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=2376
      - traefik.protocol=https
    volumes:
      - CLOUD_COMPUTER_DOCKER:$CLOUD_COMPUTER_DOCKER:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

volumes:
  CLOUD_COMPUTER_DOCKER:
