version: '3.5'

networks:
  backend:
    driver: bridge

services:

  docker:
    image: sjawhar/docker-socket-proxy:latest
    restart: always
    command:
      - -dd
      - -lmlocal2
    environment:
      CERTS_DIR: $CLOUD_COMPUTER_BACKEND/infrastructure/docker
      SERVER_CERT: cert.pem
      SERVER_KEY: key.pem
    ports:
      - 2376:2376
    volumes:
      - CLOUD_COMPUTER_BACKEND:$CLOUD_COMPUTER_BACKEND:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

volumes:
  CLOUD_COMPUTER_BACKEND:
