version: '3.5'

services:

  docker:
    image: tecnativa/docker-socket-proxy
    restart: always
    environment:
      AUTH: '1'
      BUILD: '1'
      CONTAINERS: '1'
      EXEC: '1'
      IMAGES: '1'
      NETWORKS: '1'
      POST: '1'
      SYSTEM: '1'
      VOLUMES: '1'
    expose:
      - 2375
    labels:
      - virtual.host=docker.$CLOUD_COMPUTER_HOST_DNS
      - virtual.port=2375
      - virtual.tls-email=jackson@cloud-computer.dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
