version: '3.5'

services:

  grafana:
    image: grafana/grafana:latest
    restart: always
    labels:
      namespace: grafana
      tier: cloud-computer
    environment:
      GF_SERVER_ROOT_URL: https://grafana-$CLOUD_COMPUTER_HOST_DNS
    expose:
      - 3000
    labels:
      - virtual.host=grafana.$CLOUD_COMPUTER_HOST_DNS
      - virtual.port=3000
      - virtual.tls-email=jackson@cloud-computer.dev
    volumes:
      - CLOUD_COMPUTER_GRAFANA:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    expose:
      - 3100
    labels:
      - virtual.host=loki.$CLOUD_COMPUTER_HOST_DNS
      - virtual.port=3100
      - virtual.tls-email=jackson@cloud-computer.dev

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes:
      - /var/log:/var/log

volumes:
  CLOUD_COMPUTER_GRAFANA:
