version: '3.5'

services:

  grafana:
    image: grafana/grafana:latest
    restart: always
    labels:
      namespace: grafana
      tier: cloud-computer
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_SERVER_ROOT_URL: https://grafana-$CLOUD_COMPUTER_HOST_DNS
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:grafana.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=3000
    volumes:
      - CLOUD_COMPUTER_GRAFANA:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    expose:
      - 3100
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:loki.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=3100

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes:
      - /var/log:/var/log

volumes:
  CLOUD_COMPUTER_GRAFANA:
