version: '3.5'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.8
    restart: always
    labels:
      namespace: jaeger
      tier: cloud-computer
    expose:
      - 5778
      - 14268
      - 16686
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:jaeger.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=16686
