version: '3.5'

services:

  jaeger:
    image: jaegertracing/all-in-one:1.8
    restart: always
    labels:
      namespace: jaeger
      tier: cloud-computer
    expose:
      - 5778
      - 14268
      - 16686
    labels:
      - virtual.host=jaeger.$CLOUD_COMPUTER_HOST_DNS
      - virtual.port=16686
      - virtual.tls-email=jackson@cloud-computer.dev
    volumes:
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX

volumes:
  CLOUD_COMPUTER_REPOSITORY:
  CLOUD_COMPUTER_TMUX:
