version: '3.5'

services:

  launcher:
    image: cloudnativecomputer/launcher:latest
    restart: always
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:launcher.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
