version: '3.5'

services:

  terminal:
    image: $CLOUD_COMPUTER_REGISTRY/$CLOUD_COMPUTER_IMAGE:latest
    command: yarn --cwd infrastructure/cloud-computer tmux:server
    working_dir: $CLOUD_COMPUTER_BACKEND
    restart: always
    tty: true
    labels:
      namespace: terminal
      tier: cloud-computer
    environment:
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DISPLAY: $CLOUD_COMPUTER_XEPHYR_DISPLAY
      DOCKER_HOST: localhost
      GIT_AUTHOR_EMAIL: $GIT_AUTHOR_EMAIL
      GIT_AUTHOR_NAME: $GIT_AUTHOR_NAME
      GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
      GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
      CLOUD_COMPUTER_CERTIFICATES: $CLOUD_COMPUTER_CERTIFICATES
      CLOUD_COMPUTER_CREDENTIALS: $CLOUD_COMPUTER_CREDENTIALS
      CLOUD_COMPUTER_HOST_DNS: $CLOUD_COMPUTER_HOST_DNS
      CLOUD_COMPUTER_HOST_ID: $CLOUD_COMPUTER_HOST_ID
      CLOUD_COMPUTER_HOST_NAME: $CLOUD_COMPUTER_HOST_NAME
      CLOUD_COMPUTER_HOST_USER: $CLOUD_COMPUTER_HOST_USER
      CLOUD_COMPUTER_TMUX: $CLOUD_COMPUTER_TMUX
      VIRTUAL_HOST: terminal-$CLOUD_COMPUTER_HOST_DNS:8080,debug-terminal-$CLOUD_COMPUTER_HOST_DNS:9229,frontend-$CLOUD_COMPUTER_HOST_DNS:3000
    expose:
      - 2000
      - 3000
      - 8080
      - 9229
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - CLOUD_COMPUTER_BACKEND:$CLOUD_COMPUTER_BACKEND
      - CLOUD_COMPUTER_CERTIFICATES:$CLOUD_COMPUTER_CERTIFICATES
      - CLOUD_COMPUTER_CODE:$CLOUD_COMPUTER_CODE
      - CLOUD_COMPUTER_CODE_SERVER:$CLOUD_COMPUTER_CODE_SERVER
      - CLOUD_COMPUTER_CREDENTIALS:$CLOUD_COMPUTER_CREDENTIALS
      - CLOUD_COMPUTER_FRONTEND:$CLOUD_COMPUTER_FRONTEND
      - CLOUD_COMPUTER_GITHUB:$CLOUD_COMPUTER_GITHUB
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME
      - CLOUD_COMPUTER_KUBECONFIGS:$CLOUD_COMPUTER_KUBECONFIGS
      - CLOUD_COMPUTER_NODEMON:$CLOUD_COMPUTER_NODEMON
      - CLOUD_COMPUTER_SLACKBOT:$CLOUD_COMPUTER_SLACKBOT
      - CLOUD_COMPUTER_TERRAFORM:$CLOUD_COMPUTER_TERRAFORM
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX
      - CLOUD_COMPUTER_X11:$CLOUD_COMPUTER_X11
      - CLOUD_COMPUTER_YARN:$CLOUD_COMPUTER_YARN

  container-logs:
    image: gliderlabs/logspout:latest
    restart: always
    tty: true
    labels:
      namespace: logging
      tier: cloud-computer
    environment:
      ALLOW_TTY: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  CLOUD_COMPUTER_BACKEND:
  CLOUD_COMPUTER_CERTIFICATES:
  CLOUD_COMPUTER_CODE:
  CLOUD_COMPUTER_CODE_SERVER:
  CLOUD_COMPUTER_CREDENTIALS:
  CLOUD_COMPUTER_FRONTEND:
  CLOUD_COMPUTER_GITHUB:
  CLOUD_COMPUTER_HOME:
  CLOUD_COMPUTER_KUBECONFIGS:
  CLOUD_COMPUTER_NODEMON:
  CLOUD_COMPUTER_SLACKBOT:
  CLOUD_COMPUTER_TERRAFORM:
  CLOUD_COMPUTER_TMUX:
  CLOUD_COMPUTER_X11:
  CLOUD_COMPUTER_YARN:
