version: '3.5'

networks:
  backend:
    driver: bridge

services:

  # cloud computer bootstrap

  ingress:
    image: cloud-computer/cloud-computer-ingress:latest
    restart: always
    labels:
      namespace: ingress
      tier: cloud-computer
    environment:
      VIRTUAL_HOST_SPECIFIC_PORT: 'true'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - CLOUD_COMPUTER_CERTIFICATES:$CLOUD_COMPUTER_CERTIFICATES:ro
    ports:
      - 443:443
      - 8443:8443
    networks:
      - backend

  terminal:
    image: cloud-computer/cloud-computer:latest
    command: yarn --cwd infrastructure/cloud-computer tmux:server
    working_dir: $CLOUD_COMPUTER_BACKEND
    restart: always
    tty: true
    labels:
      namespace: terminal
      tier: cloud-computer
    environment:
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DISPLAY: $CLOUD_COMPUTER_XEPHYR_DISPLAY
      DOCKER_CONFIG: $CLOUD_COMPUTER_DOCKER
      DOCKER_HOST: unix:///var/run/docker.sock
      GIT_AUTHOR_EMAIL: $GIT_AUTHOR_EMAIL
      GIT_AUTHOR_NAME: $GIT_AUTHOR_NAME
      GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
      GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
      CLOUD_COMPUTER_CERTIFICATES: $CLOUD_COMPUTER_CERTIFICATES
      CLOUD_COMPUTER_CREDENTIALS: $CLOUD_COMPUTER_CREDENTIALS
      CLOUD_COMPUTER_HOST_DNS: $CLOUD_COMPUTER_HOST_DNS
      CLOUD_COMPUTER_HOST_ID: $CLOUD_COMPUTER_HOST_ID
      CLOUD_COMPUTER_HOST_NAME: $CLOUD_COMPUTER_HOST_NAME
      CLOUD_COMPUTER_HOST_USER: $CLOUD_COMPUTER_HOST_USER
      CLOUD_COMPUTER_TMUX: $CLOUD_COMPUTER_TMUX
      TERRAFORM_TARGET: $TERRAFORM_TARGET
      VIRTUAL_HOST: terminal-$CLOUD_COMPUTER_HOST_DNS:8080,debug-terminal-$CLOUD_COMPUTER_HOST_DNS:9229,majestic-$CLOUD_COMPUTER_HOST_DNS:2000,frontend-$CLOUD_COMPUTER_HOST_DNS:3000
    expose:
      - 2000
      - 3000
      - 8080
      - 9229
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - CLOUD_COMPUTER_BACKEND:$CLOUD_COMPUTER_BACKEND
      - CLOUD_COMPUTER_CERTIFICATES:$CLOUD_COMPUTER_CERTIFICATES
      - CLOUD_COMPUTER_CODE:$CLOUD_COMPUTER_CODE
      - CLOUD_COMPUTER_CODE_SERVER:$CLOUD_COMPUTER_CODE_SERVER
      - CLOUD_COMPUTER_CREDENTIALS:$CLOUD_COMPUTER_CREDENTIALS
      - CLOUD_COMPUTER_DOCKER:$CLOUD_COMPUTER_DOCKER
      - CLOUD_COMPUTER_FRONTEND:$CLOUD_COMPUTER_FRONTEND
      - CLOUD_COMPUTER_GITHUB:$CLOUD_COMPUTER_GITHUB
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME
      - CLOUD_COMPUTER_KUBECONFIGS:$CLOUD_COMPUTER_KUBECONFIGS
      - CLOUD_COMPUTER_NODEMON:$CLOUD_COMPUTER_NODEMON
      - CLOUD_COMPUTER_SLACKBOT:$CLOUD_COMPUTER_SLACKBOT
      - CLOUD_COMPUTER_TERRAFORM:$CLOUD_COMPUTER_TERRAFORM
      - CLOUD_COMPUTER_TMUX:$CLOUD_COMPUTER_TMUX
      - CLOUD_COMPUTER_X11:$CLOUD_COMPUTER_X11
      - CLOUD_COMPUTER_YARN:$CLOUD_COMPUTER_YARN
    networks:
      - backend
    extra_hosts:
      - cloud-computer-${CLOUD_COMPUTER_HOST_DNS}:${CLOUD_COMPUTER_DEVELOPMENT_ENVIRONMENT_IP}

  xpra:
    image: sabrehagen/x11-bridge:latest
    restart: always
    tty: true
    labels:
      namespace: xpra
      tier: cloud-computer
    environment:
      MODE: tcp
      VIRTUAL_HOST: desktop-$CLOUD_COMPUTER_HOST_DNS:10000
      XPRA_ENABLE_CRYPTO: 0
      XPRA_ENCODING: png
      XPRA_MOUSE_ECHO: 0
      XPRA_HTML: 1
    expose:
      - 10000
    volumes:
      - CLOUD_COMPUTER_X11:$CLOUD_COMPUTER_X11
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:10000']
      interval: 20s
      timeout: 5s
      retries: 5

  container-logs:
    image: gliderlabs/logspout:latest
    restart: always
    tty: true
    labels:
      namespace: logging
      tier: cloud-computer
    environment:
      ALLOW_TTY: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

  netdata:
    image: netdata/netdata:latest
    command: -D -u ubuntu
    restart: always
    labels:
      namespace: monitoring
      tier: cloud-computer
    environment:
      PGID: 1000
      VIRTUAL_HOST: netdata-$CLOUD_COMPUTER_HOST_DNS
    expose:
      - 19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined

volumes:
  CLOUD_COMPUTER_BACKEND:
  CLOUD_COMPUTER_CERTIFICATES:
  CLOUD_COMPUTER_CODE:
  CLOUD_COMPUTER_CODE_SERVER:
  CLOUD_COMPUTER_CREDENTIALS:
  CLOUD_COMPUTER_DOCKER:
  CLOUD_COMPUTER_FRONTEND:
  CLOUD_COMPUTER_GITHUB:
  CLOUD_COMPUTER_HOME:
  CLOUD_COMPUTER_KUBECONFIGS:
  CLOUD_COMPUTER_NODEMON:
  CLOUD_COMPUTER_SLACKBOT:
  CLOUD_COMPUTER_TERRAFORM:
  CLOUD_COMPUTER_TMUX:
  CLOUD_COMPUTER_X11:
  CLOUD_COMPUTER_YARN:
