attach: false
name: dashboard
on_project_exit: tmux -S $CLOUD_COMPUTER_TMUX/.tmux.sock select-pane -t dashboard:1.3
on_project_first_start: tmux -S $CLOUD_COMPUTER_TMUX/.tmux.sock set-environment -g CLOUD_COMPUTER_TMUX_SESSION_ID $(date +%M%S)
pre_window: cd $CLOUD_COMPUTER_REPOSITORY/infrastructure/cloud-computer; export DOCKER_HOST=unix:///var/run/docker.sock
socket_path: $CLOUD_COMPUTER_TMUX/.tmux.sock

windows:
  - terminal:
      layout: tiled
      panes:
        - yarn --cwd infrastructure/cloud-computer logs:code
        - yarn --cwd infrastructure/cloud-computer ctop
        - . $HOME/.zlogin; yarn links
  - jest:
      layout: main-vertical
      panes:
        - yarn --cwd infrastructure/tmux jest:attach
        - git l
  - ingress:
      layout: tiled
      panes:
        - yarn --cwd infrastructure/cloud-computer logs:ingress
  - gotop:
      layout: tiled
      panes:
        - gotop
  - git:
      layout: tiled
      panes:
        - lazygit
