attach: false
name: dashboard
on_project_exit: tmux -S $CLOUD_COMPUTER_TMUX/.tmux.sock select-pane -t dashboard:1.3
on_project_first_start: tmux -S $CLOUD_COMPUTER_TMUX/.tmux.sock set-environment -g CLOUD_COMPUTER_TMUX_SESSION_ID $(date +%M%S)
root: /cloud-computer/cloud-computer/infrastructure/cloud-computer
socket_path: $CLOUD_COMPUTER_TMUX/.tmux.sock

windows:
  - terminal:
      layout: tiled
      panes:
        - yarn logs
        - yarn ctop
        - cd ../..; clear; . $HOME/.zlogin
  - jest:
      layout: main-vertical
      panes:
        - yarn tmux:jest:attach
        - yarn logs:jest
  - ingress:
      layout: tiled
      panes:
        - yarn logs:ingress
  - frontend:
      layout: even-horizontal
      panes:
        - yarn tmux:frontend:build:attach
  - communication:
      layout: tiled
      panes:
        - yarn tmux:weechat:attach
  - git:
      layout: tiled
      panes:
        - cd ../..; lazygit
